### ISSUE TITLE
Syslog Support

### ISSUE THREAD

**Issue by philipithomas** [WestleyArgentum/Lumberjack.jl#23]
Having syslog support would be nice so that we could support shipping logs to a service like Papertrail or Splunk at the application level.

**Comment by spurll** [comment]
I've actually implemented this in [Invenia's fork of Lumberjack](https://github.com/invenia/Lumberjack.jl). We will be issuing a pull request shortly.

**Comment by WestleyArgentum** [comment]
Sweet, that sounds great
