### ISSUE TITLE
Update for Julia 0.6

### ISSUE THREAD

**Issue by samtkaplan** [WestleyArgentum/Lumberjack.jl#45]
@WestleyArgentum 

Now that Julia 0.6 is released, would you mind merging pull requests #41, #42 and #44, and tagging a new version of Lumberjack.jl.  The changes in these pull requests are reasonably trivial updates to support changes in Julia 0.6.

Thanks!

Sam

**Comment by WestleyArgentum** [comment]
Tagged: https://github.com/JuliaLang/METADATA.jl/pull/10083

Hopefully will be merged shortly. Thanks, and sorry again for the delay!

**Comment by WestleyArgentum** [comment]
done!
